import { Metadata } from "next";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
};
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import AppTopBar from "./_components/app-topbar";
import { AppSidebar } from "./_components/app-sidebar";
import {
    getUserAppRole,
    getUserSession,
} from "../(auth)/_actions/getCurrentUser";

export default async function AdminLayout(
    { children }: { children: ReactNode },
) {
    const { data: { session } } = await getUserSession();

    const role = getUserAppRole(session?.access_token);

    return (
        <SidebarProvider>
            <head>
                <title>{role ?? "Dashboard"}</title>
            </head>
            <AppSidebar />
            <SidebarInset>
                <AppTopBar />
                <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                    {children}
                </div>
            </SidebarInset>
        </SidebarProvider>
    );
}
